### ISSUE TITLE
Where are the message destination Factor or Variable excluded in message aggregations?

### ISSUE THREAD

**Issue by koertkuipers** [HewlettPackard/sandpiper#3]
sorry this is not an issue at all, i just didn't see any other way to communicate.

i am looking at the source code and it looks really great! it is a pleasure to read. but i am struggling to understand one thing: when a variable sends a message to a factor its some sort of aggregation over all messages the variable received from factors **excluding the factor the message is about to be send to**. similarly when a factor sends a message to a variable it is also an aggregation over messages received from variables **excluding the variable the message is about to be send to**. where in the code do i see this exclusion behavior? i have a hard time finding it.

thanks for you help! best, koert

**Comment by avulanov** [comment]
Hi @koertkuipers. Thank you! `NamedFactor` and `NamedVariable` implement `sendMessage`. It "decomposes" a previously aggregated message from belief, for example [NamedVariable code](https://github.com/HewlettPackard/sandpiper/blob/master/src/main/scala/sparkle/graph/NamedFactor.scala#L172). The actual math is implemented in log scale in [Factor.scala](https://github.com/HewlettPackard/sandpiper/blob/master/src/main/scala/sparkle/graph/Factor.scala#L37)

**Comment by koertkuipers** [comment]
i see it now. that's why sendMessage takes in oldMessage. thanks.
